version: "3"

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - devduo:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  devduo:
