# Generated by Django 3.2.8 on 2021-10-17 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=5000)),
                ('user_name', models.CharField(max_length=5000, unique=True)),
                ('password', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=5000)),
                ('status', models.BooleanField(default=False)),
                ('fields', models.ManyToManyField(to='devduo.Field')),
                ('technologies', models.ManyToManyField(to='devduo.Technology')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='devduo.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_time', models.DateTimeField()),
                ('mentee_time', models.DateTimeField()),
                ('time_start', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('mentee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devduo.user')),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devduo.mentor')),
            ],
        ),
    ]
