# Generated by Django 3.2.8 on 2021-11-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devduo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
