# Generated by Django 3.2.8 on 2021-10-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devduo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='staus',
            field=models.CharField(choices=[('pending', 'Pe'), ('ongoing', 'Og'), ('finish', 'Fi'), ('cancel', 'Ca')], default='pending', max_length=10),
        ),
    ]
