# Generated by Django 3.2.8 on 2021-10-17 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devduo', '0002_booking_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='staus',
            new_name='status',
        ),
    ]
