# Generated by Django 3.2.8 on 2021-10-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devduo', '0003_rename_staus_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='1', max_length=5000),
        ),
    ]
