# Generated by Django 3.2.8 on 2021-10-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devduo', '0006_auto_20211018_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='mentee_id',
            new_name='mentee',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='mentor_id',
            new_name='mentor',
        ),
    ]
