# Generated by Django 3.2.8 on 2021-10-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devduo', '0007_auto_20211018_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gg_id',
            field=models.CharField(default='gg_id', max_length=5000, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
