# Generated by Django 3.2.8 on 2021-10-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devduo', '0008_auto_20211022_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='contact',
            new_name='contacts',
        ),
        migrations.AddField(
            model_name='mentor',
            name='thumnail',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
