# Generated by Django 3.2.8 on 2021-11-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devduo', '0009_auto_20211028_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='mentor',
            name='full_name',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='gg_id',
            field=models.CharField(default='gg_id', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=5000),
        ),
    ]
