# Generated by Django 3.2.8 on 2021-11-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devduo', '0011_auto_20211109_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
