# Generated by Django 3.2.8 on 2021-11-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devduo', '0012_alter_mentor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Og'), ('finish', 'Fi'), ('cancel', 'Ca')], default='ongoing', max_length=10),
        ),
    ]
