# Generated by Django 3.2.8 on 2021-11-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devduo', '0013_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
