# Generated by Django 3.2.8 on 2021-11-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devduo', '0014_alter_mentor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
