# Generated by Django 3.2.8 on 2021-11-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devduo', '0015_alter_mentor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
