# Generated by Django 3.2.8 on 2021-11-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devduo', '0017_rename_thumnail_mentor_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='mentor',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
