# Generated by Django 3.2.8 on 2021-11-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devduo', '0018_auto_20211112_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='money',
            new_name='price',
        ),
    ]
